-- MySQL Script generated by MySQL Workbench
-- Thu Dec 13 01:53:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blogdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blogdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogdb` DEFAULT CHARACTER SET utf8 ;
USE `blogdb` ;

-- -----------------------------------------------------
-- Table `blogdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogdb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_fullname` VARCHAR(255) NULL,
  `user_nickname` VARCHAR(50) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_level_access` ENUM('normal', 'operator', 'admin') NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_nickname_UNIQUE` (`user_nickname` ASC) ,
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogdb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogdb`.`posts` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `post_title` VARCHAR(255) NOT NULL,
  `post_imageurl` TEXT NULL,
  `post_description` VARCHAR(255) NULL,
  `post_content` TEXT NOT NULL,
  `post_datetime` DATETIME NOT NULL,
  `post_posted_by` INT NULL,
  PRIMARY KEY (`post_id`),
  UNIQUE INDEX `post_title_UNIQUE` (`post_title` ASC) ,
  INDEX `post_posted_by_idx` (`post_posted_by` ASC) ,
  CONSTRAINT `posted_by`
    FOREIGN KEY (`post_posted_by`)
    REFERENCES `blogdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
